In [2]:
## import packages
import pandas as pd
import numpy as np
from lenskit.algorithms import Recommender
from lenskit.algorithms.user_knn import UserUser
from util import createGrps


In [4]:
## First get the groups
# parameters for group generation
size = 20
grpNum = 20
seed = 1234567

# load user data
user_data = pd.read_csv("users.tsv", sep='\t')

# generate synthetic groups of users and display them
groups2 = createGrps(user_data, size, grpNum)
print(groups2)
print()

                                                Users
0   [1362547.0, 601431.0, 1413383.0, 356371.0, 786...
1   [1019712.0, 40296.0, 1091801.0, 335101.0, 5204...
2   [740268.0, 160302.0, 67607.0, 361826.0, 115680...
3   [612415.0, 1226479.0, 591158.0, 909351.0, 4091...
4   [952227.0, 680704.0, 637266.0, 326963.0, 10067...
5   [1362509.0, 350937.0, 904764.0, 510535.0, 9518...
6   [1072470.0, 723243.0, 830645.0, 100131.0, 2485...
7   [460769.0, 124808.0, 1104681.0, 1260753.0, 568...
8   [682526.0, 537498.0, 423460.0, 929309.0, 35093...
9   [581239.0, 1090873.0, 1430114.0, 694281.0, 538...
10  [1407698.0, 190774.0, 42896.0, 1324343.0, 1142...
11  [320725.0, 1010399.0, 1053658.0, 349945.0, 521...
12  [158834.0, 1357671.0, 969927.0, 206411.0, 8586...
13  [228233.0, 467441.0, 494088.0, 611692.0, 20665...
14  [1102912.0, 102835.0, 413911.0, 350397.0, 8302...
15  [489495.0, 1190120.0, 248568.0, 479739.0, 1446...
16  [176425.0, 85889.0, 355884.0, 332135.0, 139981...
17  [1042058.0, 1111899.0, 1

In [8]:
## Create a User-Item matrix of scores so we can apply one of the aggregation strategies
# iterate through groups generated
for i, row in groups2.iterrows():
    display(row[0])

/var/folders/vt/47mxbcvj5rd7mmyk053h49m00000gn/T/ipykernel_27912/1595750048.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  display(row[0])


array([1362547.,  601431., 1413383.,  356371.,  786149.,   38896.,
        624482.,  563704.,  185700., 1312045., 1412639.,  998930.,
        338789.,  977644.,  787793.,  829323.,  997181.,   73295.,
       1017506., 1106485.])

array([1019712.,   40296., 1091801.,  335101.,  520451.,   30054.,
        858486., 1104267.,  565277., 1136355., 1305047., 1179027.,
         16023.,  321065.,  918283.,  529566.,   15451.,  806867.,
        407770.,  953509.])

array([ 740268.,  160302.,   67607.,  361826., 1156806.,  496468.,
       1285062., 1215750., 1148870., 1190120., 1038220.,  312667.,
        854252.,  710519.,  438362.,  259224.,   36446.,  206702.,
        486052.,  439587.])

array([ 612415., 1226479.,  591158.,  909351.,   40919.,  323729.,
        118968., 1385123., 1386666., 1438100., 1430152., 1015637.,
        640417.,  279606.,  389492.,  449832.,  681611.,  542563.,
       1411229., 1201412.])

array([ 952227.,  680704.,  637266.,  326963.,  100676.,  643566.,
       1413232.,  434524., 1098268., 1442665., 1162860.,  664693.,
         18003.,  792489., 1144365.,  803633.,  755791.,   88610.,
        921120.,  106902.])

array([1362509.,  350937.,  904764.,  510535.,  951852.,  155454.,
       1343669.,  759282.,  285329.,  208776.,  916627., 1150207.,
        175665.,  591327.,  794367.,  435871.,  750637.,  527268.,
        454880.,  474026.])

array([1072470.,  723243.,  830645.,  100131.,  248511., 1034995.,
       1333991.,  291806.,  150094.,   84728.,  188775.,  608257.,
        911063.,  337930.,  411378.,  542295., 1301150.,  306790.,
         60379.,  982209.])

array([ 460769.,  124808., 1104681., 1260753.,  568325.,  160031.,
       1269634.,  915463., 1336262.,  394874.,  918854.,  416699.,
        876702., 1268100.,  632417., 1166162., 1012934.,  660090.,
        855949., 1100164.])

array([ 682526.,  537498.,  423460.,  929309.,  350937.,  515586.,
       1034199., 1062019., 1105009.,  231813.,  433665.,  551360.,
        766637.,  703528.,  632576.,   23809., 1152959., 1240832.,
        595203.,  236291.])

array([ 581239., 1090873., 1430114.,  694281.,  538996., 1377410.,
       1183365.,  520571.,  587826., 1126159.,  692330.,  655033.,
        580323., 1003013.,  608267.,  341156.,  142132.,  608653.,
       1172265., 1075364.])

array([1407698.,  190774.,   42896., 1324343., 1142795., 1307099.,
       1187159.,   79523.,  313252.,  255716.,  105897.,   93095.,
        497705., 1353303.,  317417., 1405493.,  648427.,  977249.,
        277839., 1048931.])

array([ 320725., 1010399., 1053658.,  349945.,  521010., 1031303.,
        146212.,  426568., 1149274.,  863746.,  784868.,  419989.,
       1373179.,  710765.,  208181., 1234258.,  694724.,  130379.,
        423257.,  757591.])

array([ 158834., 1357671.,  969927.,  206411.,  858681.,  301737.,
        523252., 1312065.,  348044.,  749403.,   29169., 1218249.,
        595679., 1105259.,  933849.,  373221.,  318780.,  848738.,
        340062.,   61620.])

array([ 228233.,  467441.,  494088.,  611692.,  206654., 1150526.,
       1009305., 1081110.,  416826.,  835759., 1405931.,  282768.,
       1115428., 1140268.,  337411.,  150178.,  336874.,  495647.,
       1314823.,  438154.])

array([1102912.,  102835.,  413911.,  350397.,  830265.,  226306.,
       1260574.,  467295., 1029687., 1065744., 1171756.,   19146.,
        783482.,  842640.,  357373., 1280539.,  840026.,  600330.,
        382700.,  620297.])

array([ 489495., 1190120.,  248568.,  479739., 1446449., 1148870.,
       1321862.,  812772., 1403418.,  361826.,  160302.,  393765.,
        781122., 1356380., 1468597.,  224904.,  496468.,  259224.,
        737875.,  715220.])

array([ 176425.,   85889.,  355884.,  332135.,  139981.,  910617.,
       1171537., 1035119.,  529702.,  210914., 1405386.,  499032.,
        256836., 1200068.,  759212.,  483067.,  227790.,  653999.,
        817709.,   95076.])

array([1042058., 1111899.,  194559., 1185050.,  839768., 1413911.,
        870134.,   21679., 1298959., 1282821.,  435688.,  614078.,
        633430., 1160815.,  380437.,  695470., 1221609.,   53946.,
       1188307.,  851766.])

array([ 972363.,    2186., 1166442.,  270868.,  471474., 1429320.,
        279450.,  726690., 1342124.,  503450.,  496491.,  299690.,
        995976.,  551549., 1137166.,  161336.,   57284.,  596003.,
        578120., 1440050.])

array([ 369647.,  459179.,  181069.,  680689., 1090969.,  220574.,
        736105.,  891594.,  878952.,  636813., 1035969., 1371268.,
        953844.,  903071.,  276969., 1227551., 1406093.,  392676.,
       1368972.,  903853.])